---
title: "Course Agenda"
---

| **Week** |  **Date** | **Topics** | **In Class Activities** | **Out of Class Assignments** | 
| :------- | :-------: | :--------: | :---------------------: | :--------------------------: |
| 1        | 3/29      | [Class overview and roadmap; Clinical Skills introduction](slides/cds431_week1_1.pptx) |     | Read assessment reports [20 Month EI Evaluation](handouts/20 month EI Evaluation.pdf); [27 Month Speech and Language Evaluation](handouts/27 month Speech and Language Evaluation.pdf); [3 year Developmental Evaluation](handouts/3 year Developmental Evaluation.pdf); [5 year IFSP](handouts/5 year IFSP.pdf); [HEDCO Child History Questionnaire](handouts/HEDCO Child History Questionnaire-1.pdf) and [HEDCO Assessment Report](handouts/assessment 1.pdf); Complete Survey | 
| 1        | 3/31      | [Cycles of Clinical Services: Assessment; Introduction to Case Study: Intake](slides/cds431_week1_2.pptx) | [Activities #1 and 2](handouts/In-Class Activities 2022.docx); [Terms & Definitions (TD) Log](handouts/Terms and Definitions Worksheet_blank.docx); Note: [20 Month EI Evaluation](handouts/20 month EI Evaluation.pdf); [27 Month Speech and Language Evaluation](handouts/27 month Speech and Language Evaluation.pdf); [3 year Developmental Evaluation](handouts/3 year Developmental Evaluation.pdf); [5 year IFSP](handouts/5 year IFSP.pdf); and [HEDCO Assessment Report](handouts/assessment 1.pdf) needed to complete Activity 1*     | Quiz 1 | 
| 2        | 4/5       | [Review of SSD](slides/cds431_week2_1.pptx) | Activity 3; [Minimal Pairs Example](slides/Minimal Pair Therapy.pptx)    | Quiz 2 | 
| 2        | 4/7       | [Designing Assessment; Language Sample](slides/cds431_week2_2.pptx) | Activity #4    | Quiz 3; _Begin work on Assignment #1 **Due 4/21**_ | 
| 3        | 4/12       | [Standardized Assessments; Sound Probes](slides/cds431_week3_1.pptx) | Activities # 5, 6, 7, 8; [CELF Scoring Documents](handouts/CELF scoring documents.pdf)    | Quiz 4 | 
| 3        | 4/14       | [Phonological Awareness Assessment; Interpreting Assessment Results](slides/cds431_week3_2.pptx) | Activities #9, 10, 11; [CELF Scoring Documents](handouts/CELF scoring documents.pdf)    | Quiz 5 | 
| 4        | 4/19       | [Reviewing the Assessment Report; Interpreting Results to Families](slides/cds431_week4_1.pptx) | Activity #12    | Quiz 6 | 
| 4        | 4/21       | [Reviewing the Assessment Report; Interpreting Results to Families](slides/cds431_week4_1.pptx) | Activity #12    | Quiz 6;  [**Assignment #1: Designing Assessment Due by 5:00 PM**](assignments/Assignment 1.docx) | 
| 5        | 4/26       | [EBP for Determining Treatment](slides/cds431_week5_1.pptx); [Supplementary Slides on consuming research as an SLP](slides/Translating the evidence_presentation.pptx) | Activities #13, 14    | Quiz 7 | 
| 5        | 4/28       | [Choosing a Treatment Approach; Goal Writing](slides/cds431_week5_2.pptx); [Supplementary slides on goal writing](slides/Goal Writing Practicum_Fall 2021.pptx) | Activities #15, 16; [Case Goals](handouts/Matthew's Goals.pdf); [Case Treatment Approach](handouts/Case Treatment Approach Summary.pdf)    |  | 
| 6        | 5/3       | [Preparing the Environment; Treatment Observation: Session 1; Introduction to Lesson Planning; Corrective Feedback & Parent Coaching](slides/cds431_week6_1.pptx) | Activities #17, 18; [Session 1 Lesson Plan, Home Plan, and SOAP Note](handouts/Session 1 Lesson Plan, Home Plan, and SOAP Note.pdf)    | Quiz 8 | 
| 6        | 5/5       | [Treatment Observation: Session 2; Data Collection](slides/cds431_week6_2.pptx) | Activities #19, 20; [Session 2 Lesson Plan, Home Plan, and SOAP Note](handouts/Session 2 Lesson Plan, Home Plan, and SOAP note.pdf)    | Quiz 9; ; _Begin work on Assignment #2: Lesson Plan_ | 
| 7        | 5/10       | [Treatment Observation: Session 3; Data collection](slides/cds431_week7_1.pptx) | Activities #21, 22, 23; [Session 3 Lesson Plan, Home Plan, and SOAP Note](handouts/Session 3 Lesson Plan, Home Plan, and SOAP note.pdf)    | Quiz 10; [**Assignment #2 Due by 5:00 PM**](assignments/Assignment 2.docx); _Begin work on Assignment #3: Data Collection_  | 
| 7        | 5/12       | [Treatment Observation: Session 4; Data Collection](slides/cds431_week7_2.pptx) | Activity #25; [Session 4 SOAP Note](handouts/Session 4 SOAP.pdf); [Session 5 Lesson Plan](handouts/Session 5 lesson plan.pdf)    | Quiz 11; _Begin work on Assignment #4 SOAP Note_ | 
| 8        | 5/17       |  [Progress (SOAP) Notes](slides/cds431_week8_1.pptx) | Activity #26; [Session 1 to 4 SOAP Notes](handouts/SOAPS 1to4.pdf)    | Quiz 12; [**Assignment #3 Due by 5:00 PM**](assignments/Assignment 3.docx)  | 
| 8        | 5/19      | [Ongoing Progress Monitoring](slides/cds431_week8_2.pptx) | Activity #27; [Progress Report](handouts/Progress Report-1.pdf)     | Quiz 13 | 
| 9        | 5/24      | [Service Delivery; Audiology Assessment](slides/cds431_week9_1.pptx) | Activities #28, 29; [Audiogram 1](handouts/Audiogram 1-1.pdf); [Audiogram 2](handouts/Audiogram 2.pdf)    | Quiz 14; [**Assignment #4 Due by 5:00 PM**](assignments/Assignment 4.docx)  | 
| 9        | 5/26       | [Post-Intervention; Family Conference](slides/cds431_week9_2.pptx) | Activity #30; [Progress Report](handouts/Progress Report-1.pdf)    | Quiz 15 | 
| 10        | 5/31       | Medical SLP guest panel with [Michele Vandehey](mailto:mvandeh2@uoregon.edu) and [Aaron Rothbart](mailto:arothbar@uoregon.edu) | [Survey link to add questions for the guest panel](https://oregon.qualtrics.com/jfe/form/SV_bxCEFPJrbQrvBNY)    |  | 
| 10        | 6/2       | [Client Follow-up; Dismissal Decision Making; Troubleshooting Therapy Sessions](slides/cds431_week10.pptx) |     | Quiz 16 | 
| 10        | 6/3       |  |     | [**Due by 5:00 PM: Terms & Definitions](handouts/Terms and Definitions Worksheet_blank.docx); [In-Class Activities Packet](handouts/In-Class Activities 2022.docx) | 
| Finals Week        | 6/6       |  |     | Observational Log due (optional) | 


_**Note:**_ Some in-class activities may need to be finished outside of class
