---
title: "Syllabus"
output:
  html_document:
    toc: true
    toc_float: true
---

## CDS 431: Beginning Clinical Methods 

* **Term:** Spring 2022
* **Days:** Tuesdays and Thursdays
* **Time:** 8:30 - 9:50 AM
* **Location:** HEDCO 220
* **Instructor:** Jim Wright, PhD, CCC-SLP
	+ *email:* [jwrigh16@uoregon.edu](mailto:jwrigh16@uoregon.edu)
	+ *office:* HEDDO 270
	+ *office hours*: TBD
	+ *pronouns:* "Jim"; he/him/his
	

# LEARNER OUTCOMES (COURSE OBJECTIVES)

Following this course, students will have introductory (developing) skills in:

  * Describing general assessment practices, including:
    + interpreting case history information and developing assessment plans,
    + scoring assessment protocols, and
    + interpreting assessment data to develop an evidence-based treatment plan
    
  * Describing general treatment practices, including:
    + planning treatment using evidence-based decision making, 
    + planning treatment sessions, 
    + analyzing session data to inform clinical decisions,
    + measuring treatment outcomes, and
    + identifying therapeutic practices to optimize client progress.

# COURSE STRUCTURE AND MATERIALS 

This class meets two times per week for 1-hour, 20-minute sessions. There is not a required textbook for this class.  All course materials can be found on the course Canvas site and course website, including:

  * The course syllabus 
  * Two documents of PowerPoint slides for this course
  * Case Study: in-class activities 
  * Out-of-class assignments 
  * Additional references and materials for the case study assignments
  * Observation Hours Log
  * Terms and Definition Worksheet
  
# STUDENT ENGAGEMENT HOURS 

Under the UO policy, each undergraduate credit should reflect approximately thirty hours of student engagement including in- and out-of-class activities. Therefore, a 3-credit course should engage students for approximately 90 hours total (an average of 8-hours per week). This class meets for one hour and fifteen-minutes twice per week. The additional course engagement hours (5hrs 30min per week) may include readings, preparing for discussions, completing in-class activities, written assignments, completion of quizzes outside of class time, and optional observation activities.

# COURSE ASSIGNMENTS 

Course assignments will be posted on Canvas and discussed during class. An * indicates that the assignment is required to pass the course. The following includes basic information:

  1. *Terms and Definitions: Students will complete this document during class.  Terms are indicated in purple in the PowerPoint.  You must have at least 50 terms/definitions by the end of the term.  You can print this form and handwrite the terms/definitions. Students will submit this document at the end of the term. 
  2. *Case Study - In-Class Activities: For the most part, students will complete these activities during class.  You may print the document and handwrite answers during the class. Occasionally, you will be asked to finish activities outside of class. Students will submit this completed packet at the end of the term.
  3. *Out-of-Class Assignments: These four assignments will be completed independently outside of class and should be typed into a document (assignments in Canvas).  
  4. *Group Participation Feedback: You will complete this form at midterm and end of term. 
  5. *Quizzes: There will be 16 quizzes posted on Canvas to be taken after class. Each quiz reflects content covered in class and will be open in Canvas from 10:00 am to 10:00 pm on the day of the class.  
  6. CDS 431 Observation Hour Log: An Observation Hours Log for CDS 431 will be made available for students to log their hours week 10 of the term.  More information will be presented in class. 
  7. Other Observation Document (optional): If you complete virtual observations through the HEDCO Learning Commons, you may present documentation to me for signing. Only logs with complete documentation will be signed.  If you complete observations outside of the UO, the certified SLP that you observed will sign your log. You are responsible for maintaining logs of observations completed outside of this class. If you decide to use Master Clinician Network (fee-based online service for observations), I can approve those observations through June 30, 2022.
  
  
# CASE STUDY CONFIDENTIALITY 

The parents of the case study participant graciously gave their permission for video and paper records to be used for instructional purposes within the CDS department.  Every effort should be taken to ensure the confidentiality of the case study participants.  All students will sign a case study confidentiality agreement on the first day of class.  Any breach of this agreement would be considered academic misconduct.

# GRADING POLICY 

This is a Pass/No Pass course. 

Students will be graded on the class attendance and completion of in-class activities and out-of-class assignments. In order to “pass” this course, students must: 

  1. Attend 18 of the 20 scheduled in-class sessions and complete corresponding in-class activities for the days then attend. It is the student’s responsibility to sign the attendance sheet 
  2. Complete all out-of-class assignments and receive a passing grade. If a student gets a “no-pass” on an assignment, they have one week to resubmit the assignment for a passing grade
  3. List and define at least 40 terms presented in class on the “Terms and Definitions” sheet


| **Required Assignments** | **Possible Points** | **Due Date** | 
| :----------------------  | :-----------------: | :----------: |
| Course pre-survey                     | 4      | 3/31 5:00 PM |
| Assignment 1: Designing an Assessment | 25     | 4/21 5:00 PM |
| Assignment 2: Lesson Plan             | 18     | 5/10 5:00 PM |
| Assignment 3: Data Collection Form    | 14     | 5/17 5:00 PM |
| Assignment 4: SOAP Note               | 18     | 5/24 5:00 PM |
| Terms & Definitions log - at least 50 entries | 10     | 6/3 5:00 PM |
| In-Class Activities Packet | 27                | 6/3 5:00 PM  |
| Course post-survey                  | 4        | 6/3 5:00 PM  |
| Quizzes                             | 16       |  TBA         |
| **TOTAL POSSIBLE POINTS** | 136     |  |
| **PASS** = completion of **all** assignments and earning at least 70% of total points (95) |     |  |


Students will **not pass** this course, if they:
  * do not submit any of the assignments described in the above table and Course Assignments section of the syllabus 
  * earn less than 70% of the total possible points (94 points or below) 
  * violate the Academic Misconduct Policy (more information follows), for example:
    + doing someone else's work
    + having someone else complete quizzes or assignments 
    + plagiarizing someone else's work on the out of class assignments 
    + violating the confidentiality agreement signed at the beginning of the term
    
There may be situations beyond an individual student’s control which impact completion of required assignments.  Should this happen, students should contact me as soon as possible to discuss their unique situation and plan for extensions or make-up assignments. 


# FLUIDITY, ATTENDANCE, PARTICIPATION 

As the university community continues to adjust to teaching and learning in-person in the context of the COVID-19 pandemic, course requirements, deadlines, and grading percentages are subject to change. I will be mindful of the many impacts the unfolding events related to COVID-19 may be having on you. During this unusual time, I encourage you to talk with me about what you are experiencing so we can work together to help you succeed in this course. 

# UO COVID-19 REGULATIONS & PREVENTION FOR IN-PERSON CLASS
See [here](https://coronavirus.uoregon.edu/covid-19-regulations) for more information 

The University of Oregon (UO), in accordance with guidance from the Centers for Disease Control, Oregon Health Authority, and Lane County Public Health requires faculty, staff, students, visitors, and vendors across all UO locations to use face coverings with in UO owned, leased, or controlled buildings. This includes classrooms. Please correctly wear a suitable face covering during class. Students unable to wear face coverings can work with the [Accessible Education Center](https://aec.uoregon.edu/) to find a reasonable accommodation. Students refusing to wear a face covering will be asked to leave the class. 

Face covering are not required for fully vaccinated instructors, providing there is 6 feet of distance to others and that all others in the class are masked. For full guidelines, which are subject to change, see the UO’s face covering regulations. Students should obtain wipes available outside of classrooms before they enter class and use them to wipe down the table and seat they will use. 

Please conduct regular [symptom self-checks](https://coronavirus.uoregon.edu/#before-campus) and do not come to class if you are
experiencing symptoms. I will work with you to make sure you can stay caught up with the
class. Use this [self-check log](https://coronavirus.uoregon.edu/sites/coronavirus1.uoregon.edu/files/2020-08/self-monitoring.pdf) to track your symptoms. 

# COLLEGE OF EDUCATION COVID PANDEMIC PROTOCOL 

The College of Education will follow all guidelines established by the University of Oregon.
Given the ever-evolving nature of the pandemic these guidelines are subject to change
during the year. Please see this [website](https://coronavirus.uoregon.edu/covid-19-regulations) for the most up-to-date UO policies regarding COVID 

# COLLEGE OF EDUCATION APPROACH TO ABSENCES RELATED TO COVID

For Fall of 2021 and beyond the College of Education (COE) and the University of Oregon
will be relying on high vaccination rates and safety protocols in each building to allow for a
safe, in-person return. To this end the COE course offerings for Fall 2021 and beyond is a
return to pre-COVID instructional expectations for instructors and students. This means that
instructors will once again be providing instruction in person and students who are unable to
attend class will be expected to navigate this with their instructor as a typical class absence.However, this year is unlikely to be “typical” and over the course of the quarter one or more of us may run into short or extended absences due to COVID related concerns such as the need to quarantine or care for a family member due to COVID. In order to proactively plan for these potential absences, the following plan will be in place:

All lectures will be recorded via Zoom and uploaded directly to the course Canvas site. If
students need to be absent for 2 classes or less due to a COVID related quarantine or illness,
please make sure to access the recorded lectures. You may set up an appointment to meet
with me to also go over all material missed. If students need to be absent due to a COVID
related quarantine or illness for 3 class sessions or more, please set up an appointment to
meet with me to discuss an individualized plan. Depending on student need, assignment and
exam timelines will be shifted accordingly.

There is also the possibility that I may be absent due to COVID related concerns such as
exposure, quarantining, or caring for family. If needed, lectures will shift entirely online via Zoom. For in-person experiential experiences, I will make every attempt to identify another faculty member or doctoral student who can assist with the in-person component. Information about any of these changes will be posted on Canvas as well as emailed to the class list. In order to request an accommodation for COVID related concerns students are directed to follow the process through the Accessible Education Center (AEC) which is the campus unit that will evaluate student needs to assist with providing and authorizing the necessary support. While the AEC [website](https://aec.uoregon.edu/make-appointment-aec) refers frequently to disabilities, the unit responds more generally to concerns that impact instruction including health
concerns.


# COURSE, DEPARTMENT AND UNIVERSITY POLICIES 

## INDIGENOUS RECOGNITION STATEMENT 
The University of Oregon is located on Kalapuya Ilihi, the traditional indigenous homeland of the Kalapuya people. Today, descendants are citizens of the Confederated Tribes of the Grand Ronde Community of Oregon and the Confederated Tribes of the Siletz Indians of Oregon, and they continue to make important contributions in their communities, at UO, and across the land we now refer to as Oregon.

## CDS UNDERGRADUATE PROGRAM GRADING POLICY
The CDS major is a rigorous, pre-professional major, which leads to advanced study in speech-language pathology, audiology, and related fields.  With that in mind, CDS faculty members work to ensure students gain the scientific, theoretical, and applied clinical knowledge to prepare them for future careers. Grades in the courses serve as one metric to allow graduate programs and employers to evaluate CDS graduates.


Grading in the CDS department reflects the following fundamental principles:

  * A grade, whether a final grade or one for an individual assignment, is to be determined based on objective criteria applied equally for all students.
  * Grades are assigned for the work product submitted by the student.  Faculty members are unable to evaluate or give credit for factors such as level of effort or time taken to complete an assignment.
  * Grades are based on work outlined in the course syllabus, which is available to all students.  Individual extra credit assignments will not be considered or accepted.
 
Following these principals, individual faculty members may choose assignments, grading criteria, and scales for calculation of final grades, which fit within the nature of content covered and individual philosophies.

**Regarding the assignment of final grades, the CDS faculty members agree student requests for grade changes after final grades have been posted will not granted unless an error has been made in calculating or inputting the final grade.**

This course is graded as Pass/No-Pass.  Grading procedures are detailed in this syllabus.  Please contact me immediately with any questions or concerns.  For most of you, this is your last term before graduation and you need to earn a Pass.  You are responsible for monitoring your progress in class and quickly identifying any problems or issues that might interfere with successful completion.

## ACCESSIBLE EDUCATION 

Please let me know within the first two weeks of the term if you need assistance to fully participate in the course. Participation includes access to lectures, web-based information, in-class activities, and quizzes. The [Accessible Education Center](https://aec.uoregon.edu/) works with students to provide an instructor notification letter that outlines accommodations and adjustments to class design that will enable better access. Contact the Accessible Education Center for assistance with access or disability-related questions or concerns.

## DIVERSITY, EQUITY, AND INCLUSION

It is the policy of the University of Oregon to support and value equity and diversity and to provide inclusive learning environments for all students.  To do so requires that we: 
  * respect the dignity and essential worth of all individuals. 
  * promote a culture of respect throughout the University community. 
  * respect the privacy, property, and freedom of others. 
  * reject bigotry, discrimination, violence, or intimidation of any kind. 
  * practice personal and academic integrity and expect it from others. 
  * promote the diversity of opinions, ideas and backgrounds which is the lifeblood of the university.

In this course, class discussions, projects/activities and assignments will challenge students to think critically about and be sensitive to the influence, and intersections, of race, ethnicity, nationality, documentation, language, religion, gender, socioeconomic background, physical and cognitive ability, sexual orientation, and other cultural identities and experiences. Students will be encouraged to develop or expand their respect and understanding of such differences.

Maintaining an inclusive classroom environment where all students feel able to talk about their cultural identities and experiences, ideas, beliefs, and values will not only be my responsibility, but the responsibility of each class member as well. Behavior that disregards or diminishes another student will not be permitted for any reason. This means that no racist, ableist, transphobic, xenophobic, chauvinistic or otherwise derogatory comments will be allowed. It also means that students must pay attention and listen respectfully to each other’s comments.


## USING PRONOUNS AND PERSONAL PREFERENCE 
The College of Education is always working to include and engage everyone. One way we can do this is to share your pronouns, or the words you want to be called when people aren’t using your name. Like names, pronouns are an important part of how we identify that deserves to be respected. And we recognize that assuming someone’s gender can be hurtful, especially to members of our community who are transgender, genderqueer, or non-binary. As a community, we are all learning together about the importance of pronouns and being better allies to the trans community on campus. Please discuss the pronouns you wish to be used with your professor to help them be aware of how to address you respectfully. Please visit this [university website](https://studentlife.uoregon.edu/pronouns) for more information.

## REPORTING TITLE IX EXPERIENCES 
Any student who has experienced sexual assault, relationship violence, sex or gender-based bullying, stalking, and/or sexual harassment may seek resources and help at safe.uoregon.edu. To get help by phone, a student can also call either the UO’s 24-hour hotline at 541-346-7244 [SAFE], or the non-confidential Title IX Coordinator at 541-346-8136. From the SAFE website, students may also connect to Callisto, a confidential, third-party reporting site that is not a part of the university. 

Students experiencing any other form of prohibited discrimination or harassment can find information at https://respect.uoregon.edu/ or https://aaeo.uoregon.edu/ or contact the non-confidential AAEO office at 541-346-3123 or the Dean of Students Office at 541-346-3216 for help. As UO policy has different reporting requirements based on the nature of the reported harassment or discrimination, additional information about reporting requirements for discrimination or harassment unrelated to sexual assault, relationship violence, sex or gender based bullying, stalking, and/or sexual harassment is available at http://aaeo.uoregon.edu/content/discrimination-harassment 

Specific details about confidentiality of information and reporting obligations of employees can be found at https://titleix.uoregon.edu. 

## REPORTING OBLIGATIONS 
I am a designated reporter. For information about my reporting obligations as an employee, please see [Employee Reporting Obligations](https://investigations.uoregon.edu/employee-responsibilities#employee-obligations) on the Office of Investigations and Civil Rights Compliance (OICRC) website. Students experiencing any form of prohibited discrimination or harassment, including sex or gender-based violence, may seek information and resources at safe.uoregon.edu, respect.uoregon.edu, or investigations.uoregon.edu or contact the non-confidential Title IX office/Office of Civil Rights Compliance (541-346-3123), or Dean of Students offices (541-346-3216), or call the 24-7 hotline 541-346-SAFE for help. I am also a mandatory reporter of child abuse. Please find more information at [Mandatory Reporting of Child Abuse and Neglect](https://hr.uoregon.edu/policies-leaves/general-information/mandatory-reporting-child-abuse-and-neglect).

## ACADEMIC MISCONDUCT 

The University Student Conduct Code (available at conduct.uoregon.edu) defines academic misconduct. Students are prohibited from committing or attempting to commit any act that constitutes academic misconduct. By way of example, students should not give or receive (or attempt to give or receive) unauthorized help on assignments or examinations without express permission from the instructor. Students should properly acknowledge and document all sources of information (e.g. quotations, paraphrases, ideas) and use only the sources and resources authorized by the instructor. If there is any question about whether an act constitutes academic misconduct, it is the students’ obligation to clarify the question with the instructor before committing or attempting to commit the act. Additional information about a common form of academic misconduct, plagiarism, is available at https://researchguides.uoregon.edu/citing-plagiarism.

## INCLEMENT WEATHER
It is generally expected that class will meet unless the University is officially closed for inclement weather. If it becomes necessary to cancel class while the University remains open, this will be announced on Canvas and by email. Updates on inclement weather and closure are also communicated in other ways described here: https://hr.uoregon.edu/about-hr/campus-notifications/inclement-weather/inclement-weather-immediate-updates

## ACADEMIC DISRUPTION DUE TO CAMPUS EMERGENCY 
In the event of a campus emergency that disrupts academic activities, course requirements, deadlines, and grading percentages are subject to change. Information about changes in this course will be communicated as soon as possible by email, and on Canvas. If we are not able to meet face-to-face, students should immediately log onto Canvas and read any announcements and/or access alternative assignments. Students are also encouraged to continue the readings and other assignments as outlined in this syllabus or subsequent syllabi.

## MENTAL HEALTH AND WELNESS 
Life at college can be very complicated. Students often feel overwhelmed or stressed, experience anxiety or depression, struggle with relationships, or just need help navigating challenges in their life. If you're facing such challenges, you don't need to handle them on your own--there's help and support on campus. 

As your instructor if I believe you may need additional support, I will express my concerns, the reasons for them, and refer you to resources that might be helpful. It is not my intention to know the details of what might be bothering you, but simply to let you know I care and that help is available. Getting help is a courageous thing to do—for yourself and those you care about.

University Health Services help students cope with difficult emotions and life stressors. If you need general resources on coping with stress or want to talk with another student who has been in the same place as you, visit the Duck Nest (located in the EMU on the ground floor) and get help from one of the specially trained Peer Wellness Advocates. Find out more at health.uoregon.edu/ducknest. 

University Counseling Services (UCS) has a team of dedicated staff members to support you with your concerns, many of whom can provide identity-based support. All clinical services are free and confidential. Find out more at counseling.uoregon.edu or by calling 541-346-3227 (anytime UCS is closed, the After-Hours Support and Crisis Line is available by calling this same number).

## BASIC NEEDS 
Any student who has difficulty affording groceries or accessing sufficient food to eat every day, or who lacks a safe and stable place to live and believes this may affect their performance in the course is urged to contact the Dean of Students Office (346-3216, 164 Oregon Hall) for support.
This UO webpage includes resources for food, housing, healthcare, childcare, transportation, technology, finances, and legal support: https://blogs.uoregon.edu/basicneeds/food/

**Feed the Flock - Services for Students Facing Food Insecurity**

Any student who has difficulty affording groceries or accessing sufficient food to eat every day, or who lacks a safe and stable place to live and believes this may affect their performance in the course is urged to contact the Dean of Students Office (346-3216, 164 Oregon Hall) for support.
This UO webpage includes resources for food, housing, healthcare, childcare, transportation, technology, finances, and legal support: https://blogs.uoregon.edu/basicneeds/food/

The Student Sustainability Center (@uo_ssc) will try to aggregate changes and information for all programs via facebook and Instagram. For food security specific resources, follow @feedtheflockuo. Please follow for the most up to date information regarding program changes.

  * **ECM Student Food Pantry** - Open 4-6pm Wednesdays and Thursdays. 710 E. 17th Ave. Eugene, OR 97401. Check the Student Food Pantry Facebook for updates including the possible addition of Saturday hours.
  * **Product Drops** - Free, fresh produce for students every Tuesday of the month from 3-5pm during the academic term (ie, not during Winter Break). Produce Drops take place in the EMU amphitheater rain or shine.
  * **SNAP Enrollment help** - The Student Sustainability Center and the Duck Nest are working to ensure continuity in SNAP enrollment help. SNAP enrollment drop-in hours with the Duck Nest are posted on the Duck Nest Instagram (@uo_ducknest). The SSC also has SNAP drop-in hours which are updated on their Instagram (@feedtheflockuo). Please follow the Duck Nest and the Student Sustainability Center on social media to stay up to date.
  * **Ducks Feeding Ducks** - Emergency meal dollars will remain available and can be used wherever Duck Bucks are accepted. To qualify, students must not have more than $4 in their Duck Bucks account and may not have used the program already this term. Additional funds can be received upon meeting with the Dean of Students office.
  * **Hearth to Table Meals** - Free community meals and meal preparation with professional Chef. Hearth to Table will not hold meals during finals week or Winter Break. Starting week 1, kitchen teams will be reduced to 4 people. Student volunteers must sign up in advance by emailing sisterclare@welcometocentral.net. Communal meals will continue being served with increased distance between tables and only 4 seats at each table. Total number of diners will be capped at 32. Meals are served 6:30 pm to any student for free. Check Hearth & Table facebook and Instagram for updates. Check the @feedtheflockuo Instagram for Hearth and Table updates
  * **Additional Resources via FOOD for Lane County:** 
    + Free Produce and Groceries 
      + Call FOOD for Lane County County at 541.343.2822 to find out which location best serves you
    + Hot Meals*
      + The Dining Room - 270 W 8th Ave; passing out to-go meals; M-Th 12-12:45pm
      + St. Vincent de Paul Service Station – 450 B Hwy 99 N; (18+ only); limited number of guests in the building, outdoor respite space available
      + Ebert Memorial Methodist Church – 532 C St. Springfield; passing out to-go meals Monday 8:30-10:30am & Tuesday/Thursday 8-11:15am
      + Eugene Catholic Worker 5th and Washington; Weds-Sat 8:30am-9:30am; Tuesday-Thursday 4:30pm-5pm
      + Free People! – Lamb’s Cottage at Skinner’s Butte, Eugene; Saturday Breakfast 9:15-9:45am, Saturday dinner
      + Burrito Brigade – First Christian Church; 1143 Oak Street, Eugene; Sun 11am-2pm
      + First Christian Church – 1166 Oak Street, Eugene; Sun 7:45am-9:15am
      + Food Not Bombs – 10 E. Broadway, Eugene; Friday 3pm
    + Food Pantry
      + Daily Bread – 89780 N. Game Farm Road, Eugene; 2nd and 4th Thursday, 2-6pm
    + Double Up Food Bucks! – Receive up to $10 for fruits and vegetables with SNAP at farmer’s markets when you spend $10 on your SNAP card. Go to the token vendor, spend $10 and get an additional $10!
    
*all times and dates are subject to change, please call FOOD for Lane County or check out their website for the most up to date information 


## ACCOMMODATION FOR RELIGIOUS OBSERVATION
The university makes reasonable accommodations, upon request, for students who are unable to attend a class for religious obligations or observance reasons, in accordance with the university discrimination policy which says “Any student who, because of religious beliefs, is unable to attend classes on a particular day shall be excused from attendance requirements and from any examination or other assignment on that day. The student shall make up the examination or other assignment missed because of the absence.” To request accommodations for this course for religious observance, visit the Office of the Registrar's website (https://registrar.uoregon.edu/calendars/religious-observances) and complete and submit to the instructor the “Student Religious Accommodation Request” form prior to the end of the second week of the term.

## CONFLICT RESOLUTION 
Several options, both informal and formal, are available to resolve conflicts for students who believe they have been subjected to or have witnessed bias, unfairness, or other improper treatment. 

It is important to exhaust the administrative remedies available to you including discussing the conflict with the specific individual, contacting the Department Head, or within the College of Education, fall term you can contact the Associate Dean for Academic Affairs, Lillian Duran, 541-346-2502, lduran@uoregon.edu. Outside the College, you can contact: 
  * UO Bias Response Team: 346-3216 http://bias.uoregon.edu/whatbrt.htm 
  * Conflict Resolution Services 346-3216 http://studentlife.uoregon.edu/support
  * Affirmative Action and Equal Opportunity: 346-3123 http://aaeo.uoregon.edu/

## GRIEVANCE POLICY 
A student or group of students of the College of Education may appeal decisions or actions pertaining to admissions, programs, evaluation of performance and program retention and completion. Students who decide to file a grievance should follow University student grievance procedures (https://policies.uoregon.edu/grievance-procedures) and/or consult with the College Associate Dean for Academic Affairs (Lillian Duran, 346-2502, lduran@uoregon.edu).


## COURSE INCOMPLETE POLICY 
Students are expected to be familiar with university policy regarding grades of “incomplete” and the timeline for completion. For details on the policy and procedures regarding incompletes, Please see: https://education.uoregon.edu/academics/incompletes-courses

